### PR TITLE
ENH: added ui file and added options

### PR DESCRIPTION
**Pull request by che85**
- medial axis can be extended to object boundary depending on crest spokes
- additionally, the original model can be selected for loading

## UI

image

### CODE REVIEW

**Comment by bpaniagua** [comment]
@vicory please review. I am pleased with the change, nice work, @che85

**Comment by che85** [comment]
We can discuss. Maybe it would even be better to have the extended medial axis as an additional output in the `InitSRepFromSPHARM` module. @vicory also mentioned in our last meeting that you guys are considering supporting s-rep visualization with the `ShapePopulationViewer` which would make this PR unnecessary. Refactoring the code would be useful either way since there is a lot of duplication happening (e.g. loading polydata etc.). 

Implementing it in the`ShapePopulationViewer` would be very useful I think.

**Comment by bpaniagua** [comment]
@vicory, I think we can integrate this change, even if we include this into SPV. Can you please confirm?

**Comment by vicory** [comment]
Closing, superseded by #49

**Pull request closed without merging**
